# Generated by Django 5.1.3 on 2024-11-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_customcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcomponent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customComponents', to='employee_app.employee'),
        ),
    ]
